import type { CatalogCategory, CatalogProduct } from "@marketplace/shared/contracts/api";

export const fallbackCategories: CatalogCategory[] = [
  { slug: "stationery", name: "Stationery" },
  { slug: "prints", name: "Prints" },
  { slug: "home", name: "Home" },
  { slug: "desk", name: "Desk" },
  { slug: "kitchen", name: "Kitchen" },
  { slug: "accessories", name: "Accessories" },
  { slug: "apparel", name: "Apparel" },
  { slug: "outdoors", name: "Outdoors" },
];

const seedTimestamp = (minutesAgo: number): string => {
  const base = Date.parse("2026-02-01T12:00:00.000Z");
  return new Date(base - minutesAgo * 60_000).toISOString();
};

export const fallbackProducts: CatalogProduct[] = [
  {
    id: "prd_seed_grid_notebook",
    vendor_id: "ven_seed_north",
    title: "Grid Notebook",
    description: "A minimal notebook with soft cover and grid pages.",
    category_slug: "stationery",
    tags: ["notebook", "paper", "grid"],
    price_incl_tax_cents: 2200,
    currency: "USD",
    stock_qty: 75,
    rating_average: 4.8,
    created_at: seedTimestamp(0),
  },
  {
    id: "prd_seed_weekly_planner",
    vendor_id: "ven_seed_north",
    title: "Desk Weekly Planner",
    description: "Weekly planner with clean blocks and bold date markers.",
    category_slug: "stationery",
    tags: ["planner", "desk"],
    price_incl_tax_cents: 1800,
    currency: "USD",
    stock_qty: 41,
    rating_average: 4.5,
    created_at: seedTimestamp(30),
  },
  {
    id: "prd_seed_dotgrid_pocket_journal",
    vendor_id: "ven_seed_north",
    title: "Dot-Grid Pocket Journal",
    description: "Pocket journal with dot grid pages and a sturdy soft cover.",
    category_slug: "stationery",
    tags: ["journal", "dot-grid", "pocket"],
    price_incl_tax_cents: 2400,
    currency: "USD",
    stock_qty: 60,
    rating_average: 4.6,
    created_at: seedTimestamp(45),
  },
  {
    id: "prd_seed_mechanical_pencil_set",
    vendor_id: "ven_seed_north",
    title: "Mechanical Pencil Set (2 pack)",
    description: "Two precise mechanical pencils with a clean matte finish.",
    category_slug: "desk",
    tags: ["pencil", "writing", "desk"],
    price_incl_tax_cents: 1600,
    currency: "USD",
    stock_qty: 120,
    rating_average: 4.4,
    created_at: seedTimestamp(60),
  },
  {
    id: "prd_seed_minimal_icon_stickers",
    vendor_id: "ven_seed_north",
    title: "Sticker Sheet: Minimal Icons",
    description: "A small sheet of crisp icon stickers for planners and notes.",
    category_slug: "stationery",
    tags: ["stickers", "planner"],
    price_incl_tax_cents: 900,
    currency: "USD",
    stock_qty: 220,
    rating_average: 4.3,
    created_at: seedTimestamp(75),
  },
  {
    id: "prd_seed_monochrome_poster",
    vendor_id: "ven_seed_linepress",
    title: "Monochrome Poster Print",
    description: "Museum-grade paper print for modern workspaces.",
    category_slug: "prints",
    tags: ["poster", "print", "art"],
    price_incl_tax_cents: 4800,
    currency: "USD",
    stock_qty: 19,
    rating_average: 4.9,
    created_at: seedTimestamp(90),
  },
  {
    id: "prd_seed_ceramic_cup",
    vendor_id: "ven_seed_linepress",
    title: "Ceramic Coffee Cup",
    description: "Hand-glazed cup built for everyday use.",
    category_slug: "home",
    tags: ["home", "ceramic", "cup"],
    price_incl_tax_cents: 3200,
    currency: "USD",
    stock_qty: 33,
    rating_average: 4.4,
    created_at: seedTimestamp(105),
  },
  {
    id: "prd_seed_risograph_blue_hour",
    vendor_id: "ven_seed_linepress",
    title: "Risograph Print: Blue Hour",
    description: "Two-color risograph print with soft ink texture and clean lines.",
    category_slug: "prints",
    tags: ["risograph", "print", "art"],
    price_incl_tax_cents: 5200,
    currency: "USD",
    stock_qty: 14,
    rating_average: 4.8,
    created_at: seedTimestamp(120),
  },
  {
    id: "prd_seed_desk_calendar",
    vendor_id: "ven_seed_linepress",
    title: "Desk Calendar (12 months)",
    description: "A desk calendar with generous whitespace and bold dates.",
    category_slug: "stationery",
    tags: ["calendar", "desk"],
    price_incl_tax_cents: 2600,
    currency: "USD",
    stock_qty: 42,
    rating_average: 4.6,
    created_at: seedTimestamp(150),
  },
  {
    id: "prd_seed_tea_towel_graph_check",
    vendor_id: "ven_seed_linepress",
    title: "Tea Towel: Graph Check",
    description: "Woven cotton towel with a subtle grid pattern.",
    category_slug: "home",
    tags: ["kitchen", "towel", "home"],
    price_incl_tax_cents: 2000,
    currency: "USD",
    stock_qty: 70,
    rating_average: 4.5,
    created_at: seedTimestamp(165),
  },

  // Koi Workshop
  {
    id: "prd_seed_cable_clips",
    vendor_id: "ven_seed_koi",
    title: "Aluminum Cable Clips",
    description: "Keep charging cables and cords anchored without adhesive mess.",
    category_slug: "desk",
    tags: ["cables", "organize", "desk"],
    price_incl_tax_cents: 1500,
    currency: "USD",
    stock_qty: 110,
    rating_average: 4.5,
    created_at: seedTimestamp(190),
  },
  {
    id: "prd_seed_desk_tray",
    vendor_id: "ven_seed_koi",
    title: "Hardwood Desk Tray",
    description: "A slim catch-all tray for keys, pens, and daily carry.",
    category_slug: "desk",
    tags: ["tray", "wood", "desk"],
    price_incl_tax_cents: 5400,
    currency: "USD",
    stock_qty: 18,
    rating_average: 4.9,
    created_at: seedTimestamp(205),
  },
  {
    id: "prd_seed_enamel_pin_sunset",
    vendor_id: "ven_seed_koi",
    title: "Enamel Pin (Sunset)",
    description: "Small enamel pin with a bright color pop for bags and jackets.",
    category_slug: "accessories",
    tags: ["pin", "enamel"],
    price_incl_tax_cents: 1200,
    currency: "USD",
    stock_qty: 200,
    rating_average: 4.3,
    created_at: seedTimestamp(220),
  },
  {
    id: "prd_seed_canvas_tote",
    vendor_id: "ven_seed_koi",
    title: "Canvas Tote Bag",
    description: "Midweight tote with reinforced handles and interior pocket.",
    category_slug: "accessories",
    tags: ["tote", "canvas", "bag"],
    price_incl_tax_cents: 3600,
    currency: "USD",
    stock_qty: 44,
    rating_average: 4.6,
    created_at: seedTimestamp(235),
  },
  {
    id: "prd_seed_keyring_carabiner",
    vendor_id: "ven_seed_koi",
    title: "Keyring Carabiner",
    description: "Compact carabiner keyring for easy carry and quick access.",
    category_slug: "accessories",
    tags: ["keyring", "carabiner"],
    price_incl_tax_cents: 1300,
    currency: "USD",
    stock_qty: 150,
    rating_average: 4.4,
    created_at: seedTimestamp(250),
  },

  // Sunbeam Supply
  {
    id: "prd_seed_spice_jar_set",
    vendor_id: "ven_seed_sunbeam",
    title: "Glass Spice Jar Set",
    description: "Four glass jars with minimalist labels and tight-seal lids.",
    category_slug: "kitchen",
    tags: ["spices", "jars", "kitchen"],
    price_incl_tax_cents: 4200,
    currency: "USD",
    stock_qty: 26,
    rating_average: 4.7,
    created_at: seedTimestamp(265),
  },
  {
    id: "prd_seed_pourover_filters",
    vendor_id: "ven_seed_sunbeam",
    title: "Pour-Over Coffee Filters",
    description: "Bright white paper filters sized for standard drippers.",
    category_slug: "kitchen",
    tags: ["coffee", "filters"],
    price_incl_tax_cents: 1100,
    currency: "USD",
    stock_qty: 140,
    rating_average: 4.5,
    created_at: seedTimestamp(280),
  },
  {
    id: "prd_seed_maple_cutting_board",
    vendor_id: "ven_seed_sunbeam",
    title: "Maple Cutting Board",
    description: "A durable cutting board with a soft matte finish.",
    category_slug: "kitchen",
    tags: ["cutting-board", "maple", "kitchen"],
    price_incl_tax_cents: 6800,
    currency: "USD",
    stock_qty: 15,
    rating_average: 4.8,
    created_at: seedTimestamp(295),
  },
  {
    id: "prd_seed_linen_napkins",
    vendor_id: "ven_seed_sunbeam",
    title: "Soft Linen Napkins (2 pack)",
    description: "Everyday linen napkins in a warm neutral tone.",
    category_slug: "home",
    tags: ["linen", "napkins", "home"],
    price_incl_tax_cents: 2600,
    currency: "USD",
    stock_qty: 62,
    rating_average: 4.6,
    created_at: seedTimestamp(310),
  },
  {
    id: "prd_seed_soap_bar_citrus_cedar",
    vendor_id: "ven_seed_sunbeam",
    title: "Soap Bar (Citrus + Cedar)",
    description: "Simple, gentle soap with a fresh scent profile.",
    category_slug: "home",
    tags: ["soap", "bath"],
    price_incl_tax_cents: 900,
    currency: "USD",
    stock_qty: 190,
    rating_average: 4.4,
    created_at: seedTimestamp(325),
  },

  // Fern Atelier
  {
    id: "prd_seed_relaxed_crew_tee",
    vendor_id: "ven_seed_fern",
    title: "Relaxed Crew Tee",
    description: "Soft cotton tee with a clean cut and minimal branding.",
    category_slug: "apparel",
    tags: ["t-shirt", "cotton"],
    price_incl_tax_cents: 4200,
    currency: "USD",
    stock_qty: 38,
    rating_average: 4.5,
    created_at: seedTimestamp(340),
  },
  {
    id: "prd_seed_ribbed_beanie",
    vendor_id: "ven_seed_fern",
    title: "Ribbed Beanie",
    description: "Warm ribbed knit beanie for cold morning walks.",
    category_slug: "apparel",
    tags: ["beanie", "knit"],
    price_incl_tax_cents: 2800,
    currency: "USD",
    stock_qty: 55,
    rating_average: 4.6,
    created_at: seedTimestamp(355),
  },
  {
    id: "prd_seed_trail_socks",
    vendor_id: "ven_seed_fern",
    title: "Trail Socks (2 pack)",
    description: "Cushioned socks built for long days on your feet.",
    category_slug: "outdoors",
    tags: ["socks", "trail"],
    price_incl_tax_cents: 2400,
    currency: "USD",
    stock_qty: 80,
    rating_average: 4.7,
    created_at: seedTimestamp(370),
  },
  {
    id: "prd_seed_compact_rain_poncho",
    vendor_id: "ven_seed_fern",
    title: "Compact Rain Poncho",
    description: "Lightweight poncho that packs down into a small pouch.",
    category_slug: "outdoors",
    tags: ["rain", "poncho", "packable"],
    price_incl_tax_cents: 3900,
    currency: "USD",
    stock_qty: 34,
    rating_average: 4.4,
    created_at: seedTimestamp(385),
  },
  {
    id: "prd_seed_canvas_cap",
    vendor_id: "ven_seed_fern",
    title: "Canvas Cap",
    description: "A structured cap with subtle stitching and a clean profile.",
    category_slug: "accessories",
    tags: ["cap", "hat"],
    price_incl_tax_cents: 3100,
    currency: "USD",
    stock_qty: 48,
    rating_average: 4.3,
    created_at: seedTimestamp(400),
  },

  // Moss & Mortar
  {
    id: "prd_seed_stoneware_planter",
    vendor_id: "ven_seed_moss",
    title: "Stoneware Planter",
    description: "Small stoneware planter with drainage hole and saucer.",
    category_slug: "home",
    tags: ["planter", "stoneware"],
    price_incl_tax_cents: 5200,
    currency: "USD",
    stock_qty: 17,
    rating_average: 4.8,
    created_at: seedTimestamp(415),
  },
  {
    id: "prd_seed_wool_picnic_blanket",
    vendor_id: "ven_seed_moss",
    title: "Wool Picnic Blanket",
    description: "A warm blanket with a simple stripe pattern for outdoor hangs.",
    category_slug: "outdoors",
    tags: ["blanket", "wool", "picnic"],
    price_incl_tax_cents: 8900,
    currency: "USD",
    stock_qty: 9,
    rating_average: 4.9,
    created_at: seedTimestamp(430),
  },
  {
    id: "prd_seed_incense_cones_sandalwood",
    vendor_id: "ven_seed_moss",
    title: "Incense Cones (Sandalwood)",
    description: "Gentle incense cones for a calm evening ritual.",
    category_slug: "home",
    tags: ["incense", "sandalwood"],
    price_incl_tax_cents: 1600,
    currency: "USD",
    stock_qty: 105,
    rating_average: 4.5,
    created_at: seedTimestamp(445),
  },
  {
    id: "prd_seed_plant_mister",
    vendor_id: "ven_seed_moss",
    title: "Plant Mister Spray Bottle",
    description: "Fine-mist sprayer for keeping plants happy year-round.",
    category_slug: "home",
    tags: ["plants", "mister"],
    price_incl_tax_cents: 2300,
    currency: "USD",
    stock_qty: 46,
    rating_average: 4.4,
    created_at: seedTimestamp(460),
  },
  {
    id: "prd_seed_leather_notebook_cover",
    vendor_id: "ven_seed_moss",
    title: "Leather Field Notebook Cover",
    description: "A slim leather cover to protect your daily carry notebook.",
    category_slug: "accessories",
    tags: ["leather", "notebook", "cover"],
    price_incl_tax_cents: 7600,
    currency: "USD",
    stock_qty: 12,
    rating_average: 4.7,
    created_at: seedTimestamp(475),
  },
];

export const fallbackVendorNameByID: Record<string, { id: string; slug: string; displayName: string }> = {
  ven_seed_north: {
    id: "ven_seed_north",
    slug: "north-studio",
    displayName: "North Studio",
  },
  ven_seed_linepress: {
    id: "ven_seed_linepress",
    slug: "line-press",
    displayName: "Line Press",
  },
  ven_seed_koi: {
    id: "ven_seed_koi",
    slug: "koi-workshop",
    displayName: "Koi Workshop",
  },
  ven_seed_sunbeam: {
    id: "ven_seed_sunbeam",
    slug: "sunbeam-supply",
    displayName: "Sunbeam Supply",
  },
  ven_seed_fern: {
    id: "ven_seed_fern",
    slug: "fern-atelier",
    displayName: "Fern Atelier",
  },
  ven_seed_moss: {
    id: "ven_seed_moss",
    slug: "moss-and-mortar",
    displayName: "Moss & Mortar",
  },
};
